# EORI of local satellite
id: <SATELLITE_EORI>

# Private key of local satellite
key: |
  -----BEGIN RSA PRIVATE KEY-----
  <Satellite private key>
  -----END RSA PRIVATE KEY-----

# Certificate chain of local satellite
crt: |
  -----BEGIN CERTIFICATE-----
  <Satellite certificate>
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  <Intermediate certificates>
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  <Root CA certificate>
  -----END CERTIFICATE-----

# Configuration of trusted list
trusted_list:
  - name: iSHARETestCA
    status: "granted"
    validity: "valid"
    crt: |
      -----BEGIN CERTIFICATE-----
      <iSHARETestCA Certificate>
      -----END CERTIFICATE-----
      
  - name: FIWARETEST-CA
    status: "granted"
    validity: "valid"
    crt: |
      -----BEGIN CERTIFICATE-----
      <FIWARETEST-CA Certificate>
      -----END CERTIFICATE-----

# Configuration of parties
parties:
  - id: "EU.EORI.NLPACKETDEL"
    did: "did:key:z6Mkv4Lh9zBTPLoFhLHHMFJA7YAeVw5HFYZV8rkdfY9fNtm3"
    name: "Packet Delivery Company"
    status: "Active"
    start_date: "2021-09-27T00:00:00Z"
    end_date: "2051-09-27T00:00:00Z"
    crt: |
      -----BEGIN CERTIFICATE-----
      <Packet Delivery Company Certificate>
      -----END CERTIFICATE-----
    capability_url: "https://idp.packetdel.com/capabilities" # Optional
    certifications: # Optional
      - role: "IdentityProvider"
        start_date: "2021-09-27T00:00:00Z"
        end_date: "2051-09-27T00:00:00Z"
        loa: 3
  
  - id: "EU.EORI.NLNOCHEAPER"
    name: "NoCheaper"
    status: "Active"
    start_date: "2021-09-27T00:00:00Z"
    end_date: "2051-09-27T00:00:00Z"
    crt: |
      -----BEGIN CERTIFICATE-----
      <NoCheaper Certificate>
      -----END CERTIFICATE-----
    capability_url: "https://idp.packetdel.com/capabilities" # Optional
    certifications: # Optional
      - role: "IdentityProvider"
        start_date: "2021-09-27T00:00:00Z"
        end_date: "2051-09-27T00:00:00Z"
        loa: 3

  - id: "EU.EORI.NLHAPPYPETS"
    name: "HappyPets"
    status: "NotActive"
    start_date: "2021-09-27T00:00:00Z"
    end_date: "2051-09-27T00:00:00Z"
    crt: |
      -----BEGIN CERTIFICATE-----
      <HappyPets Certificate>
      -----END CERTIFICATE-----
